creation_rules:
  - encrypted_regex: '^(data|stringData)$'
    path_regex: ./environment-overlays/dev/.*
    kms: 'arn:aws:kms:us-east-1:950698127059:key/a2033cc0-fa97-41ea-9f33-d03266745335'
  - encrypted_regex: '^(data|stringData)$'
    path_regex: ./bigbang-base/.*
    kms: 'arn:aws:kms:us-east-1:950698127059:key/a2033cc0-fa97-41ea-9f33-d03266745335'
